server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://root:123456@1.117.241.40:27017/test?authSource=admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd